services:
  - type: web
    name: docuchat-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn docuchat_backend.app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PORT
        value: "8000"
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALG
        value: "HS256"
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: "gpt-4o-mini"
      - key: DATABASE_URL
        value: "sqlite:///./docuchat_backend/docuchat.db"
      - key: CHROMA_DB_DIR
        value: "docuchat_backend/chroma_db"
      - key: CHROMA_COLLECTION
        value: "docuchat"

  - type: web
    name: docuchat-ui
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app_streamlit.py --server.port 10000 --server.address 0.0.0.0"
    envVars:
      - key: PORT
        value: "10000"
      - key: API_BASE
        # 👇 IMPORTANT: after the API service deploys,
        # replace this with your actual public URL for docuchat-api.
        # e.g. "https://docuchat-api.onrender.com"
        value: "http://localhost:8000"
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_MODEL
        value: "gpt-4o-mini"
